spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
#          uri: file:///${PWD}/../../../../../spring-configs
          uri: https://github.com/alexisLoison/spring-configs/tree/master
  rabbitmq:
    host: rabbitmq

server:
  port: 8888
  
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      