spring:
  application:
    name: teacher
  rabbitmq:
    dynamic: true
    port: 5672
    username: guest
    password: guest
    host: localhost
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: test-consumer-group
    
logging:
  pattern:
    console: '%d{mm:ss.SSS} %-5p [%-31t] [%-54logger{0}] %marker%m%ex{full} - %logger - %F:%L%n'
  level:
    org:
      springframework:
        amqp: TRACE
    root: warn
    
server:
  port: 2222    
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
      

---
server:
  port: 2222
  
spring:
  profiles: docker
  application:
    name: teacher
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true